# -----------
# EXPLICACIÓN
# -----------

# ⚙️ "settings.py" este es el archivo más importante después de tus apps. Acá se configura todo: desde la base de datos 
# que vas a usar, las apps instaladas, hasta el idioma, la zona horaria, archivos estáticos, plantillas, etc. Es como el 
# panel de control de tu proyecto. Si querés cambiar algo global, como ponerlo en español como hicimos antes, es acá.

# --------------------------------------------------------------------------------------------------------------------- #


# Django settings for Prueba project.

# Generated by 'django-admin startproject' using Django 6.0.1.

# For more information on this file, see:
# https://docs.djangoproject.com/en/6.0/topics/settings/

# For the full list of settings and their values, see:
# https://docs.djangoproject.com/en/6.0/ref/settings/


from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See: https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1*t1=bcxhvljqk_aw_mb3k6#r1z#b_^qabptlhtk%slad1yipo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition:

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'HolaMundo',  # ⚠️ Agregamos nuestra app HolaMundo al proyecto.
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PRUEBA.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PRUEBA.wsgi.application'


# Database:
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation:
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization:
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# ⚠️ CAMBIO 1: Idioma de inglés USA a español Argentina
# ------------------------------------------------------
# Antes: LANGUAGE_CODE = 'en-us'
# Ahora: LANGUAGE_CODE = 'es-ar'
# ¿Qué hace?: Cambia todos los textos automáticos de Django (mensajes, 
# etiquetas, validaciones) de inglés a español con modismos argentinos.
LANGUAGE_CODE = 'es-ar'

# ⚠️ CAMBIO 2: Zona horaria de UTC a Argentina/Buenos Aires
# ----------------------------------------------------------
# Antes: TIME_ZONE = 'UTC'
# Ahora: TIME_ZONE = 'America/Argentina/Buenos_Aires'
# ¿Qué hace?: Configura la zona horaria para que las fechas y horas
# se muestren correctamente según el huso horario de Argentina.
TIME_ZONE = 'America/Argentina/Buenos_Aires'

# ⚠️ CAMBIO 3: Estas dos líneas YA EXISTEN, NO LAS MODIFIQUES
# ------------------------------------------------------------
# USE_I18N = True  -> Activa el sistema de internacionalización (traducciones).
# USE_TZ = True    -> Activa el soporte de zonas horarias.
USE_I18N = True

USE_TZ = True

# ✅ OPCIÓN MEJORADA (comentada por si la querés probar):
# Si querés un control más fino sobre los formatos, podés agregar:
# USE_L10N = True  # Usa formatos locales para fechas y números (día/mes/año).
# DATE_FORMAT = 'd/m/Y'  # Formato personalizado: 31/12/2024.
# DATETIME_FORMAT = 'd/m/Y H:i'  # Formato: 31/12/2024 15:30.

# Static files (CSS, JavaScript, Images):
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'